-- 영화 상세 정보 컬럼 추가
ALTER TABLE movies
ADD COLUMN VOTE_AVERAGE DOUBLE COMMENT '평점' AFTER BACKDROP_PATH,
ADD COLUMN CAST VARCHAR(500) COMMENT '배우 정보' AFTER VOTE_AVERAGE,
ADD COLUMN DIRECTOR VARCHAR(255) COMMENT '감독' AFTER CAST,
ADD COLUMN RUNTIME INT COMMENT '상영 시간(분)' AFTER DIRECTOR,
ADD COLUMN RELEASE_DATE VARCHAR(50) COMMENT '개봉일' AFTER RUNTIME,
ADD COLUMN CERTIFICATION VARCHAR(50) COMMENT '관람 등급' AFTER RELEASE_DATE,
ADD COLUMN BUDGET BIGINT COMMENT '예산' AFTER CERTIFICATION,
ADD COLUMN REVENUE BIGINT COMMENT '수익' AFTER BUDGET;
