-- 컨텐츠 타입 및 추가 정보 컬럼 추가
ALTER TABLE netplix.movies
ADD COLUMN CONTENT_TYPE VARCHAR(20) DEFAULT 'dvd' COMMENT '컨텐츠 타입: dvd 또는 movie' AFTER REVENUE,
ADD COLUMN TRAILER_URL VARCHAR(500) COMMENT '예고편 URL (YouTube)' AFTER CONTENT_TYPE,
ADD COLUMN OTT_PROVIDERS VARCHAR(500) COMMENT 'OTT 제공 플랫폼' AFTER TRAILER_URL,
ADD COLUMN COLLECTION_NAME VARCHAR(500) COMMENT '시리즈/컬렉션 정보' AFTER OTT_PROVIDERS,
ADD COLUMN RECOMMENDATIONS TEXT COMMENT '추천 영화' AFTER COLLECTION_NAME,
ADD COLUMN TOP_REVIEW TEXT COMMENT '대표 리뷰' AFTER RECOMMENDATIONS;

-- 기존 데이터는 모두 dvd로 설정
UPDATE netplix.movies SET CONTENT_TYPE = 'dvd' WHERE CONTENT_TYPE IS NULL;

-- content_type 인덱스 추가 (조회 성능 향상)
CREATE INDEX idx_content_type ON netplix.movies(CONTENT_TYPE);
