spring:
  datasource:
    hikari:
      # 로컬: Docker MySQL (DB_HOST 미설정 시 localhost). Heroku: JawsDB/ClearDB 등 추가 후 DB_HOST, DB_PORT, DB_NAME 설정
      jdbc-url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:netplix}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useSSL=${DB_USE_SSL:false}&allowPublicKeyRetrieval=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    open-in-view: false
    show-sql: true
  flyway:
    locations: classpath:flyway
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true
